### ISSUE TITLE
Some services are not able to be constructed

### ISSUE THREAD

**Issue by Jonatthu** [benmccallum/fairybread#55]
Using 7.rc1

When using:
```
	public class AddLimitOrderInputValidator : AbstractValidator<AddLimitOrderInput>, IRequiresOwnScopeValidator
	{
		public AddLimitOrderInputValidator(TradingDbContext db)
		{
		}
	}
```

The next exception get's thrown

```
Exception has occurred: CLR/System.AggregateException
Exception thrown: 'System.AggregateException' in Microsoft.Extensions.DependencyInjection.dll: 'Some services are not able to be constructed'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.InvalidOperationException : Unable to resolve service for type 'Trading.EntryPoint.Data.TradingDbContext' while attempting to activate 'Trading.EntryPoint.Schema.LimitOrders.Mutations.AddLimitOrderInputValidator'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
```

**Comment by benmccallum** [comment]
Hi @Jonatthu , do you get this on v6? I imagine so as nothing has changed on the DI front but just wanted to check.

Beyond that, it's a bit hard to know what's going wrong here. It's likely an issue with your DI configuration. If you can produce a small repo, that would be great.

Will be interesting to see how you're registering your DbContext and the validator, specifically what their lifetime configured is.
